/* Wikimedia Commons photo manifest for MLB Ballparks Quest.
   Images are local resized/compressed WebP derivatives; see PHOTO_CREDITS.md for source and license details. */
(function attachParkPhotos(global) {
  var namespace = global.BPQ || (global.BPQ = {});
  namespace.parkPhotos = {
    "chase-field": { src: "assets/parks/chase-field.webp", alt: "Chase Field ballpark photograph", credit: "U.S. Air Force photo by Staff Sgt. Tyler J. Bolken", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Reserve_A-10_Warthogs_Flyover_2023_World_Series_(8099146).jpg", source: "Reserve_A-10_Warthogs_Flyover_2023_World_Series_(8099146).jpg", changes: "Resized and compressed to WebP for this static site." },
    "truist-park": { src: "assets/parks/truist-park.webp", alt: "Truist Park ballpark photograph", credit: "TarheelBornBred", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourceUrl: "https://commons.wikimedia.org/wiki/File:Truist_Park_2025.jpg", source: "Truist_Park_2025.jpg", changes: "Resized and compressed to WebP for this static site." },
    "camden-yards": { src: "assets/parks/camden-yards.webp", alt: "Oriole Park at Camden Yards ballpark photograph", credit: "Chris6d", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Camden_Yards.jpg", source: "Camden_Yards.jpg", changes: "Resized and compressed to WebP for this static site." },
    "fenway-park": { src: "assets/parks/fenway-park.webp", alt: "Fenway Park ballpark photograph", credit: "U.S. Air Force photo by Rick Berry", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:131023-F-PR861-033_Hanscom_participates_in_World_Series_pregame_events.jpg", source: "131023-F-PR861-033_Hanscom_participates_in_World_Series_pregame_events.jpg", changes: "Resized and compressed to WebP for this static site." },
    "wrigley-field": { src: "assets/parks/wrigley-field.webp", alt: "Wrigley Field ballpark photograph", credit: "Sea Cow", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Wrigley_Field_in_line_with_sign.jpg", source: "Wrigley_Field_in_line_with_sign.jpg", changes: "Resized and compressed to WebP for this static site." },
    "guaranteed-rate-field": { src: "assets/parks/guaranteed-rate-field.webp", alt: "Guaranteed Rate Field ballpark photograph", credit: "Another Believer", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Chicago,_Illinois,_U.S._(2023)_-_062.jpg", source: "Chicago,_Illinois,_U.S._(2023)_-_062.jpg", changes: "Resized and compressed to WebP for this static site." },
    "great-american-ball-park": { src: "assets/parks/great-american-ball-park.webp", alt: "Great American Ball Park ballpark photograph", credit: "Laslovarga", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:10Cincinnati_2015_(2).jpg", source: "10Cincinnati_2015_(2).jpg", changes: "Resized and compressed to WebP for this static site." },
    "progressive-field": { src: "assets/parks/progressive-field.webp", alt: "Progressive Field ballpark photograph", credit: "Erik Drost", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cleveland_Guardians_vs._New_York_Yankees_on_Oct_17_2024_(54102149292).jpg", source: "Cleveland_Guardians_vs._New_York_Yankees_on_Oct_17_2024_(54102149292).jpg", changes: "Resized and compressed to WebP for this static site." },
    "coors-field": { src: "assets/parks/coors-field.webp", alt: "Coors Field ballpark photograph", credit: "Thelastcanadian", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Coors_Field_July_2015.jpg", source: "Coors_Field_July_2015.jpg", changes: "Resized and compressed to WebP for this static site." },
    "comerica-park": { src: "assets/parks/comerica-park.webp", alt: "Comerica Park ballpark photograph", credit: "MJCdetroit", license: "CC BY-SA 3.0", licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/", sourceUrl: "https://commons.wikimedia.org/wiki/File:Detroit_Tigers_opening_game_at_Comerica_Park,_2007.jpg", source: "Detroit_Tigers_opening_game_at_Comerica_Park,_2007.jpg", changes: "Resized and compressed to WebP for this static site." },
    "minute-maid-park": { src: "assets/parks/minute-maid-park.webp", alt: "Minute Maid Park ballpark photograph", credit: "Another Believer", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Houston,_Texas_(2024)_-_09.jpg", source: "Houston,_Texas_(2024)_-_09.jpg", changes: "Resized and compressed to WebP for this static site." },
    "kauffman-stadium": { src: "assets/parks/kauffman-stadium.webp", alt: "Kauffman Stadium ballpark photograph", credit: "Chibears85", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Kauffman2017.jpg", source: "Kauffman2017.jpg", changes: "Resized and compressed to WebP for this static site." },
    "angel-stadium": { src: "assets/parks/angel-stadium.webp", alt: "Angel Stadium ballpark photograph", credit: "CrispyCream27", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Angelstadiummarch2019.jpg", source: "Angelstadiummarch2019.jpg", changes: "Resized and compressed to WebP for this static site." },
    "dodger-stadium": { src: "assets/parks/dodger-stadium.webp", alt: "Dodger Stadium ballpark photograph", credit: "Spatms", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Dodger_Stadium_and_Chavez_Ravine_far_view,_Chicago_Cubs_at_Los_Angeles_Dodgers,_(April_12,_2025).jpg", source: "Dodger_Stadium_and_Chavez_Ravine_far_view,_Chicago_Cubs_at_Los_Angeles_Dodgers,_(April_12,_2025).jpg", changes: "Resized and compressed to WebP for this static site." },
    "loandepot-park": { src: "assets/parks/loandepot-park.webp", alt: "loanDepot park ballpark photograph", credit: "Ven-Lib", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:LOAN_DEPOT_PARK.jpg", source: "LOAN_DEPOT_PARK.jpg", changes: "Resized and compressed to WebP for this static site." },
    "american-family-field": { src: "assets/parks/american-family-field.webp", alt: "American Family Field ballpark photograph", credit: "Carol M. Highsmith / Library of Congress", license: "Public domain", licenseUrl: "", sourceUrl: "https://commons.wikimedia.org/wiki/File:Miller_Park_in_Milwaukee,_Wisconsin.jpg", source: "Miller_Park_in_Milwaukee,_Wisconsin.jpg", changes: "Resized and compressed to WebP for this static site." },
    "target-field": { src: "assets/parks/target-field.webp", alt: "Target Field ballpark photograph", credit: "Ken Lund from Reno, Nevada, USA", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Target_Field,_Minneapolis,_Minnesota_(43167053335).jpg", source: "Target_Field,_Minneapolis,_Minnesota_(43167053335).jpg", changes: "Resized and compressed to WebP for this static site." },
    "citi-field": { src: "assets/parks/citi-field.webp", alt: "Citi Field ballpark photograph", credit: "Jeffme", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourceUrl: "https://commons.wikimedia.org/wiki/File:Citi_Field_from_the_south_2025.jpg", source: "Citi_Field_from_the_south_2025.jpg", changes: "Resized and compressed to WebP for this static site." },
    "yankee-stadium": { src: "assets/parks/yankee-stadium.webp", alt: "Yankee Stadium ballpark photograph", credit: "vtravelled.com", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Yankee_Stadium_overhead_2010.jpg", source: "Yankee_Stadium_overhead_2010.jpg", changes: "Resized and compressed to WebP for this static site." },
    "sutter-health-park": { src: "assets/parks/sutter-health-park.webp", alt: "Sutter Health Park ballpark photograph", credit: "Quintin Soloviev", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Sutter_Health_Park_aerial_view_2023_(Quintin_Soloviev).jpg", source: "Sutter_Health_Park_aerial_view_2023_(Quintin_Soloviev).jpg", changes: "Resized and compressed to WebP for this static site." },
    "citizens-bank-park": { src: "assets/parks/citizens-bank-park.webp", alt: "Citizens Bank Park ballpark photograph", credit: "Chris6d", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Citizens_Bank_Park_2021.jpg", source: "Citizens_Bank_Park_2021.jpg", changes: "Resized and compressed to WebP for this static site." },
    "pnc-park": { src: "assets/parks/pnc-park.webp", alt: "PNC Park ballpark photograph", credit: "Joshua Peacock jcpeacock", license: "CC0", licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en", sourceUrl: "https://commons.wikimedia.org/wiki/File:Pittsburgh_Pirates_park_(Unsplash).jpg", source: "Pittsburgh_Pirates_park_(Unsplash).jpg", changes: "Resized and compressed to WebP for this static site." },
    "petco-park": { src: "assets/parks/petco-park.webp", alt: "Petco Park ballpark photograph", credit: "Mds08011", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Petco_Park_Padres_Game.jpg", source: "Petco_Park_Padres_Game.jpg", changes: "Resized and compressed to WebP for this static site." },
    "oracle-park": { src: "assets/parks/oracle-park.webp", alt: "Oracle Park ballpark photograph", credit: "Chris6d", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Oracle_Park_2021.jpg", source: "Oracle_Park_2021.jpg", changes: "Resized and compressed to WebP for this static site." },
    "t-mobile-park": { src: "assets/parks/t-mobile-park.webp", alt: "T-Mobile Park ballpark photograph", credit: "MyName (Cacophony)", license: "CC BY-SA 3.0", licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/", sourceUrl: "https://commons.wikimedia.org/wiki/File:SafecoFieldTop.jpg", source: "SafecoFieldTop.jpg", changes: "Resized and compressed to WebP for this static site." },
    "busch-stadium": { src: "assets/parks/busch-stadium.webp", alt: "Busch Stadium ballpark photograph", credit: "Lightmetro", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Busch_Stadium_2022.jpg", source: "Busch_Stadium_2022.jpg", changes: "Resized and compressed to WebP for this static site." },
    "tropicana-field": { src: "assets/parks/tropicana-field.webp", alt: "Tropicana Field ballpark photograph", credit: "Vmartin12", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:PXL_20220528_205520913.jpg", source: "PXL_20220528_205520913.jpg", changes: "Resized and compressed to WebP for this static site." },
    "globe-life-field": { src: "assets/parks/globe-life-field.webp", alt: "Globe Life Field ballpark photograph", credit: "slgckgc", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:GlobeLifeField2021.jpg", source: "GlobeLifeField2021.jpg", changes: "Resized and compressed to WebP for this static site." },
    "rogers-centre": { src: "assets/parks/rogers-centre.webp", alt: "Rogers Centre ballpark photograph", credit: "JFVoll", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rogers_Centre_(500_Level)_-_Toronto,_ON.jpg", source: "Rogers_Centre_(500_Level)_-_Toronto,_ON.jpg", changes: "Resized and compressed to WebP for this static site." },
    "nationals-park": { src: "assets/parks/nationals-park.webp", alt: "Nationals Park ballpark photograph", credit: "APK", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Nationals_Park_8.16.19_-_7.jpg", source: "Nationals_Park_8.16.19_-_7.jpg", changes: "Resized and compressed to WebP for this static site." }
  };
})(window);
